name: 🚀 Deploy to http://skillsphere.great-site.net
on:
  push:
    branches:
      - master # change if using a different branch

jobs:
  ftp-deploy:
    name: 📤 Upload to Subdomain Directory
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 📤 FTP Deploy to skillsphere.great-site.net
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
